---
abstract: 'IO::Async support for the memcached protocol'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-Memcached
requires:
  IO::Async::Stream: 0.40
  Mixin::Event::Dispatch: 0.001
  Protocol::Memcached: 0.002
  parent: 0
version: 0.001
